name: build-test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]  # Disabled multiple executions of different node versions as github actions are executed concurrently

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run pretest
      - run: npm test
        env:
          HYPOTHESIS_TOKEN: ${{ secrets.HYPOTHESIS_TOKEN }}
          HYPOTHESIS_TEST_GROUP_ID: ${{ secrets.HYPOTHESIS_TEST_GROUP_ID }}
          HYPOTHESIS_TEST_ONLY_READ_GROUP: ${{ secrets.HYPOTHESIS_TEST_ONLY_READ_GROUP }}
